export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const CREATE_PARCEL_SUCCESS = "CREATE_PARCEL_SUCCESS"
export const CREATE_PARCEL_FAILURE = "CREATE_PARCEL_FAILURE"
export const GETPARCELS_PARCEL_FAILURE = "GETPARCELS_PARCEL_FAILURE"
export const GETPARCELS_PARCEL_SUCCESS = "GETPARCELS_PARCEL_SUCCESS"